angle_fea_len: 80
batch_size: 4
bond_fea_len: 80
checkpoint_every: 1
embedding: false
epochs: 1000
gamma: 0.5
h_fea_angle: 256
h_fea_edge: 256
learning_rate: 0.01
n_classification: 6
n_conv_edge: 1
neighbors: 15
num_workers: 1
pin_memory: true
rcut: 6
resume: true
search_delta: 20
search_type: global
step_size: 100
test_size: 0
train_size: 9600
val_size: 600
